# Generated by Django 3.2.7 on 2021-10-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstanse_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstanse',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
